#!/usr/bin/env python3

import hashlib
import tkinter as tk


def encrypt_password(password):
    password_hash = hashlib.sha256(password.encode('utf-8')).hexdigest()
    return password_hash


def register():
    register = tk.Toplevel()

    register.geometry("600x400")

    fname_var = tk.StringVar()
    sname_var = tk.StringVar()
    age_var = tk.StringVar()
    passw_var = tk.StringVar()

    def submit():
        fname = fname_var.get()
        sname = sname_var.get()
        age = age_var.get()
        password = passw_var.get()

        print(f"got: {fname} {sname} {age} {password} ")

        with open("passwords.txt", "w") as file:
            username = fname[:3] + sname[:3] + age
            encrypted_password = encrypt_password(password)
            file.write(f'{username}:{encrypted_password}\n')

        fname_var.set("")
        sname_var.set("")
        age_var.set("")
        passw_var.set("")

    fname_label = tk.Label(register, text='First name',
                           font=('calibre', 10, 'bold'))
    fname_entry = tk.Entry(register, textvariable=fname_var,
                           font=('calibre', 10, 'normal'))
    sname_label = tk.Label(register, text='Last name',
                           font=('calibre', 10, 'bold'))
    sname_entry = tk.Entry(register, textvariable=sname_var,
                           font=('calibre', 10, 'normal'))
    age_label = tk.Label(register, text='Age', font=('calibre', 10, 'bold'))
    age_entry = tk.Entry(register, textvariable=age_var,
                         font=('calibre', 10, 'normal'))
    passw_label = tk.Label(register, text='Password',
                           font=('calibre', 10, 'bold'))
    passw_entry = tk.Entry(register, textvariable=passw_var,
                           font=('calibre', 10, 'normal'), show='*')
    sub_btn = tk.Button(register, text='Submit', command=submit)

    fname_label.grid(row=0, column=0)
    fname_entry.grid(row=0, column=1)
    sname_label.grid(row=1, column=0)
    sname_entry.grid(row=1, column=1)
    age_label.grid(row=2, column=0)
    age_entry.grid(row=2, column=1)
    passw_label.grid(row=3, column=0)
    passw_entry.grid(row=3, column=1)
    sub_btn.grid(row=4, column=1)

    register.mainloop()


def login():
    login = tk.Toplevel()
    login.geometry("600x400")

    name_var = tk.StringVar()
    passw_var = tk.StringVar()

    def submit():

        username = name_var.get()
        password = passw_var.get()
        encrypted_password = encrypt_password(password)

        with open("passwords.txt", "r") as file:
            for x in file:
                if x.strip() == f'{username}:{encrypted_password}':
                    print("Password is valid!")
                    return None
            print("Password is invalid!")

        name_var.set("")
        passw_var.set("")

    username_label = tk.Label(login, text='Username',
                              font=('calibre', 10, 'bold'))
    username_entry = tk.Entry(
        login, textvariable=name_var, font=('calibre', 10, 'normal'))
    passw_label = tk.Label(login, text='Password',
                           font=('calibre', 10, 'bold'))
    passw_entry = tk.Entry(login, textvariable=passw_var,
                           font=('calibre', 10, 'normal'), show='*')
    sub_btn = tk.Button(login, text='Submit', command=submit)

    username_label.grid(row=0, column=0)
    username_entry.grid(row=0, column=1)
    passw_label.grid(row=1, column=0)
    passw_entry.grid(row=1, column=1)
    sub_btn.grid(row=2, column=1)

    login.mainloop()


root = tk.Tk()

login_button = tk.Button(root,
                         text="Login",
                         command=login,
                         activebackground="blue",
                         activeforeground="white",
                         anchor="center",
                         bd=3,
                         bg="lightgray",
                         cursor="hand2",
                         disabledforeground="gray",
                         fg="black",
                         font=("Arial", 12),
                         height=2,
                         highlightbackground="black",
                         highlightcolor="green",
                         highlightthickness=2,
                         justify="center",
                         overrelief="raised",
                         padx=10,
                         pady=5,
                         width=15,
                         wraplength=100)

login_button.pack(padx=20, pady=20)

register_button = tk.Button(root,
                            text="Register",
                            command=register,
                            activebackground="blue",
                            activeforeground="white",
                            anchor="center",
                            bd=3,
                            bg="lightgray",
                            cursor="hand2",
                            disabledforeground="gray",
                            fg="black",
                            font=("Arial", 12),
                            height=2,
                            highlightbackground="black",
                            highlightcolor="green",
                            highlightthickness=2,
                            justify="center",
                            overrelief="raised",
                            padx=10,
                            pady=5,
                            width=15,
                            wraplength=100)

register_button.pack(padx=20, pady=20)

root.mainloop()
